# Generated by Django 5.2 on 2025-05-04 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0003_alter_usersdatamodel_usercategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='driverDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleName', models.CharField(max_length=200)),
                ('VehicleCustomerLimit', models.CharField(max_length=10)),
                ('Vehicle', models.CharField(max_length=100)),
                ('VehicleNo', models.CharField(max_length=100)),
                ('VUDM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.usersdatamodel')),
            ],
        ),
    ]
