# Generated by Django 5.2 on 2025-05-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdatamodel',
            name='DriverStatus',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
