# Generated by Django 5.2 on 2025-05-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0003_driverdatamodel_drivertotaltripcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdatamodel',
            name='DriverTotalTripCount',
            field=models.IntegerField(default=0),
        ),
    ]
