# Generated by Django 5.2 on 2025-05-17 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0004_alter_driverdatamodel_drivertotaltripcount'),
        ('Users', '0006_usersdatamodel_couponcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdatamodel',
            name='DriverTotalTripCount',
        ),
        migrations.CreateModel(
            name='driveDataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DriverTotalTripCount', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.usersdatamodel')),
            ],
        ),
    ]
