# Generated by Django 5.2 on 2025-05-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0005_remove_driverdatamodel_drivertotaltripcount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModelStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CouponCode', models.CharField(max_length=50)),
                ('DriverName', models.CharField(max_length=1000)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
            ],
        ),
    ]
