# Generated by Django 5.2 on 2025-05-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0006_drivermodelstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermodelstore',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='drivermodelstore',
            name='Time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
