# Generated by Django 5.2 on 2025-05-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0007_alter_drivermodelstore_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAcceptedPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceAccepted', models.IntegerField()),
                ('pinBarCode', models.CharField(max_length=100)),
                ('userCode', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
