# Generated by Django 5.2 on 2025-05-26 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0008_driveracceptedpin'),
        ('taxi_app', '0011_pintaxiavailable_drivercode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDriverInPinTaxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverCode', models.CharField(max_length=100)),
                ('driverReportFor', models.CharField(default='default', max_length=5000)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('pinBarCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_app.pintaxiavailable')),
            ],
        ),
    ]
