# Generated by Django 5.2 on 2025-05-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0009_reportdriverinpintaxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdriverinpintaxi',
            name='reportData',
            field=models.CharField(default='default data', max_length=5000),
        ),
        migrations.AlterField(
            model_name='reportdriverinpintaxi',
            name='driverReportFor',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
