# Generated by Django 5.2 on 2025-05-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishreviewbycustomer',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='finishreviewbycustomer',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='managementmodel',
            name='dateOfChecking',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='managementmodel',
            name='timeOfChecking',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentmanagement',
            name='dateOfFairTaken',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentmanagement',
            name='timeOfFairTaken',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taxiavailable',
            name='taxiDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taxiavailable',
            name='taxiTime',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taxionfinish',
            name='taxiDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taxionfinish',
            name='taxiFinishTime',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taxitimeover',
            name='toDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taxitimeover',
            name='toTime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
