# Generated by Django 5.2 on 2025-05-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0003_taxibarcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxiavailable',
            old_name='diverId',
            new_name='customerId',
        ),
    ]
