# Generated by Django 5.2 on 2025-05-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0004_rename_diverid_taxiavailable_customerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiavailable',
            name='taxiPassenger',
            field=models.IntegerField(default=1),
        ),
    ]
