# Generated by Django 5.2 on 2025-05-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0005_taxiavailable_taxipassenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiavailable',
            name='couponCodeWas',
            field=models.CharField(default='Customer Not Have Coupon', max_length=100),
        ),
    ]
