# Generated by Django 5.2 on 2025-05-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_usersdatamodel_usercode'),
        ('taxi_app', '0006_taxiavailable_couponcodewas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaxiAvailable',
            new_name='PinTaxiAvailable',
        ),
    ]
