# Generated by Django 5.2 on 2025-05-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0007_rename_taxiavailable_pintaxiavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintaxiavailable',
            name='toLocation',
            field=models.CharField(default='No Area Found!', max_length=2000),
        ),
    ]
