# Generated by Django 5.2 on 2025-05-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0008_pintaxiavailable_tolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintaxiavailable',
            name='taxiDateAndTimeByUser',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
