# Generated by Django 5.2 on 2025-05-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0009_pintaxiavailable_taxidateandtimebyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintaxiavailable',
            name='priceOfTravel',
            field=models.IntegerField(default=100),
        ),
    ]
