# Generated by Django 5.2 on 2025-05-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0010_pintaxiavailable_priceoftravel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintaxiavailable',
            name='driverCode',
            field=models.CharField(default='DRIVERCODE', max_length=100),
        ),
    ]
