# Generated by Django 5.2 on 2025-06-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0011_pintaxiavailable_drivercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pintaxiavailable',
            name='priceOfTravel',
            field=models.IntegerField(default=0),
        ),
    ]
