# Generated by Django 5.2 on 2025-06-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0012_alter_pintaxiavailable_priceoftravel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintaxiavailable',
            name='runningStatus',
            field=models.CharField(choices=[('not', 'not'), ('yes', 'yes')], default='not', max_length=100),
        ),
    ]
