# Generated by Django 5.2 on 2025-06-12 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0013_pintaxiavailable_runningstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxionrunning',
            name='datOfTripStart',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='taxionrunning',
            name='timeOfTripStart',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
