# Generated by Django 5.2 on 2025-06-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0014_taxionrunning_datoftripstart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxionrunning',
            name='OTP_Here',
            field=models.CharField(default='NA', max_length=6),
        ),
    ]
