# Generated by Django 5.2 on 2025-06-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0015_taxionrunning_otp_here'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxionrunning',
            name='statusHideOrOpen',
            field=models.CharField(choices=[('hide', 'hide'), ('open', 'open')], default='hide', max_length=100),
        ),
    ]
