# Generated by Django 5.0.6 on 2025-06-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0016_taxionrunning_statushideoropen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxionrunning',
            name='taxiDriverName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='taxitimeover',
            name='toStatus',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Failed', max_length=20),
        ),
    ]
