# Generated by Django 5.2 on 2025-05-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdatamodel',
            name='MobileNo',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
