# Generated by Django 5.2 on 2025-05-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_usersdatamodel_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdatamodel',
            name='UserCategory',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Customer', 'Customer'), ('Driver', 'Driver')], default='Customer'),
        ),
    ]
