# Generated by Django 5.2 on 2025-05-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_usersdatamodel_usercategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersdatamodel',
            old_name='MobileNo',
            new_name='UserMobileNo',
        ),
        migrations.AddField(
            model_name='usersdatamodel',
            name='UserAddress',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usersdatamodel',
            name='UserAge',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='usersdatamodel',
            name='UserCity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usersdatamodel',
            name='UserGender',
            field=models.CharField(default='Not Check', max_length=100),
        ),
        migrations.AddField(
            model_name='usersdatamodel',
            name='UserPincode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usersdatamodel',
            name='UserState',
            field=models.CharField(default='', max_length=100),
        ),
    ]
