# Generated by Django 5.2 on 2025-05-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_rename_mobileno_usersdatamodel_usermobileno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdatamodel',
            name='UserPass',
            field=models.CharField(default='password', max_length=1000),
        ),
    ]
