# Generated by Django 5.2 on 2025-05-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_usersdatamodel_userpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdatamodel',
            name='CouponCode',
            field=models.CharField(default='', max_length=50),
        ),
    ]
