# Generated by Django 5.2 on 2025-05-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_usersdatamodel_couponcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdatamodel',
            name='CouponCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
