# Generated by Django 5.2 on 2025-05-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_usersdatamodel_couponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdatamodel',
            name='UserCode',
            field=models.CharField(default='BIGTAXICODE1006463', max_length=100),
        ),
    ]
