# Generated by Django 5.2 on 2025-05-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_usersdatamodel_usercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdatamodel',
            name='UProfileImage',
            field=models.ImageField(default='profile/default/default.png', upload_to='profile/main/'),
        ),
    ]
