# Generated by Django 5.2 on 2025-05-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_usersdatamodel_uprofileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAndRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('userCode', models.CharField(max_length=100)),
                ('ratingBarCode', models.CharField(max_length=1000)),
                ('userReview', models.CharField(max_length=5000)),
                ('userStart', models.IntegerField(default=0)),
                ('ratingDate', models.DateField(auto_now_add=True)),
                ('ratingTime', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
