# Generated by Django 5.2 on 2025-05-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_reviewbarcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdatamodel',
            name='UProfileName',
            field=models.CharField(default='BiXTaxi User', max_length=1000),
        ),
    ]
