# Generated by Django 5.2 on 2025-05-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_usersdatamodel_uprofilename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rCode', models.CharField(max_length=100)),
                ('uCode', models.CharField(max_length=100)),
                ('usernames', models.CharField(max_length=500)),
                ('rStar', models.IntegerField(default=1)),
                ('rReview', models.CharField(max_length=5000)),
                ('rDate', models.DateField(auto_now_add=True)),
                ('ratingTime', models.TimeField(auto_now_add=True)),
                ('userCategorySection', models.CharField(default='Customer', max_length=100)),
            ],
        ),
    ]
