# Generated by Django 5.2 on 2025-05-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_reviewdelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdatamodel',
            name='description',
            field=models.CharField(default='No Description!', max_length=5000),
        ),
        migrations.AddField(
            model_name='usersdatamodel',
            name='totalTripCount',
            field=models.IntegerField(default=0),
        ),
    ]
