# Generated by Django 5.2 on 2025-05-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_usersdatamodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdatamodel',
            name='dangerTripCount',
            field=models.IntegerField(default=0),
        ),
    ]
