# Generated by Django 5.2 on 2025-06-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_usersdatamodel_dangertripcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(choices=[('LOGIN_USER', 'LOGIN_USER'), ('NOT_LOGIN_USER', 'NOT_LOGIN_USER')], default='NOT_LOGIN_USER', max_length=100)),
                ('uNamesAre', models.CharField(default='NA', max_length=500)),
                ('barCode', models.CharField(default='NOBARCODE1001', max_length=100)),
                ('errorAre', models.CharField(max_length=5000)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('urls', models.CharField(default='NO_URL', max_length=2000)),
            ],
        ),
    ]
