# Generated by Django 5.0.6 on 2025-06-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_errorwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdatamodel',
            name='UserCategory',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Customer', 'Customer'), ('Driver', 'Driver')], default='Customer', max_length=20),
        ),
    ]
