# Generated by Django 5.2 on 2025-05-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PinDeleteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleteType', models.CharField(choices=[('report', 'report'), ('normal', 'normal')], default='normal', max_length=15)),
                ('pinBarCode', models.CharField(max_length=100)),
                ('userBarCode', models.CharField(max_length=100)),
                ('driverCode', models.CharField(default='DRIVERCODE', max_length=100)),
                ('review', models.CharField(default='No Report, Delete By User', max_length=100)),
                ('addressFrom', models.CharField(max_length=5000)),
                ('addressTo', models.CharField(max_length=5000)),
                ('date_Time', models.CharField(max_length=100)),
                ('passenger', models.CharField(max_length=100)),
                ('price', models.CharField(default='No Price', max_length=100)),
                ('discountCoupon', models.CharField(default='Customer Not Have Coupon', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
