# Generated by Django 5.2 on 2025-05-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PinDeleteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinBarCode', models.CharField(max_length=100)),
                ('userBarCode', models.CharField(max_length=100)),
                ('driverCode', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=100)),
                ('addressFrom', models.CharField(max_length=5000)),
                ('addressTo', models.CharField(max_length=5000)),
                ('date_Time', models.CharField(max_length=100)),
                ('passenger', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discountCoupon', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
