# Generated by Django 5.2 on 2025-05-05 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0004_rename_mobileno_usersdatamodel_usermobileno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cutomerDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalTripCount', models.IntegerField(default=0)),
                ('userName', models.CharField(default='Big Taxi User', max_length=100)),
                ('userImage', models.ImageField(default='customer/default/logo.png', max_length=1000, upload_to='customer/exist/')),
                ('description', models.CharField(default='No Description!', max_length=2000)),
                ('UDM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.usersdatamodel')),
            ],
        ),
    ]
